### ISSUE TITLE
Fehler beim testen mit CLion

### ISSUE THREAD

**Issue by stanbos0815** [ob-algdati-ws19/ob-algdati-ws19#3]
Wenn ich versuche die tests aus der main.cpp bei Blatt 5 oder 4 zu starten bekomme ich folgende Fehlermeldung, leider liefert Google keine Lösung mit der ich arbeiten konnte. Haben Sie vielleicht einen Tipp für mich was ich dagegen tun kann? Ebenfalls scheint 
# include <debugapi.h> zu fehlen..

In file included from C:\Users\Thorsten\CLionProjects\blatt-5-stanbos0815\cmake-build-debug\googletest-src\googletest\src\gtest-all.cc:41:
C:/Users/Thorsten/CLionProjects/blatt-5-stanbos0815/cmake-build-debug/googletest-src/googletest/src/gtest.cc:86:11: fatal error: crtdbg.h: No such file or directory
 # include <crtdbg.h>  // NOLINT
           ^~~~~~~~~~
compilation terminated.
mingw32-make.exe[3]: *** [googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
googletest-build\googletest\CMakeFiles\gtest.dir\build.make:62: recipe for target 'googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj' failed
mingw32-make.exe[2]: *** [googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
CMakeFiles\Makefile2:192: recipe for target 'googletest-build/googletest/CMakeFiles/gtest.dir/all' failed
CMakeFiles\Makefile2:272: recipe for target 'test/CMakeFiles/testList.dir/rule' failed
mingw32-make.exe[1]: *** [test/CMakeFiles/testList.dir/rule] Error 2
mingw32-make.exe: *** [testList] Error 2
Makefile:226: recipe for target 'testList' failed

**Comment by obcode** [comment]
wie führen Sie die Tests aus? Über das Test-Target?

**Comment by stanbos0815** [comment]
Ich habe die main.ccp der tests laufen lassen. Es lag am Compiler ich hatte MinGW und MSVC benutzt. Beide gingen nicht jetzt habe ich mit Cygwin compiliert und alles lief perfekt. Falls jemand auch dieses Problem haben sollte, hier der Link wie man Cygwin für CLion installiert: [https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html](url)
